---

#3. Use Ansible to configure your 'primary Ethernet interface' as follows:
#Eth6 701-703
#switchport mode:           trunk
#trunk native VLAN:        VLAN1
#trunk allowed VLANs:    <the three VLANs created in exercise1>

- name: Arista trunking
  hosts: arista

  tasks:
    - name: Configure Ethernet6 to trunk #remember, have to use full IF name
      eos_switchport: name=Ethernet6 mode=trunk trunk_native_vlan=1 trunk_allowed_vlans=701-703
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          port={{ eapi_port }}
          transport=https
